name: "Tests"

permissions:
  actions: write

on:
  push:
    branches:
      - master
      - dev
  pull_request:
  workflow_dispatch:

jobs:
  builds-and-tests:
    strategy:
      matrix:
        os: [windows-latest]
        
    name: ${{ matrix.os }}-${{ matrix.target }}

    runs-on: ${{ matrix.os }}

    steps:
    - name: Cancel Previous Runs
      uses: styfle/cancel-workflow-action@0.11.0
      with:
        access_token: ${{ github.token }}

    # Checkout 
    - name: checkout (Windows)
      uses: actions/checkout@v3
      with:
        path: ${{ env.PULMTLN_TOP_DIR }}
      
        